1.89.2
/usr/lib
/usr/lib/libgjs.so.0.0.0
/usr/lib/pkgconfig
/usr/lib/pkgconfig/gjs-1.0.pc
/usr/lib/gjs/girepository-1.0
/usr/lib/gjs/girepository-1.0/GjsPrivate-1.0.typelib
/usr/lib/libgjs.so.0
/usr/lib/libgjs.so
/usr/share/installed-tests/gjs
/usr/share/installed-tests/gjs/testGDBus.test
/usr/share/installed-tests/gjs/throw.test
/usr/share/installed-tests/gjs/down-up.test
/usr/share/installed-tests/gjs/throw-ignored.test
/usr/share/installed-tests/gjs/testNamespace.test
/usr/share/installed-tests/gjs/testGObjectValue.test
/usr/share/installed-tests/gjs/testGlobal.test
/usr/share/installed-tests/gjs/testGIMarshalling.test
/usr/share/installed-tests/gjs/breakpoint.test
/usr/share/installed-tests/gjs/testGLib.test
/usr/share/installed-tests/gjs/testLegacyGtk.test
/usr/share/installed-tests/gjs/testGtk4.test
/usr/share/installed-tests/gjs/keys.test
/usr/share/installed-tests/gjs/until.test
/usr/share/installed-tests/gjs/list.test
/usr/share/installed-tests/gjs/testTweener.test
/usr/share/installed-tests/gjs/testParamSpec.test
/usr/share/installed-tests/gjs/testPrint.test
/usr/share/installed-tests/gjs/sourcemap-dynamic-module.test
/usr/share/installed-tests/gjs/testGio.test
/usr/share/installed-tests/gjs/sourcemap-separate-module.test
/usr/share/installed-tests/gjs/testGtk3.test
/usr/share/installed-tests/gjs/testPackage.test
/usr/share/installed-tests/gjs/testLegacyByteArray.test
/usr/share/installed-tests/gjs/testLegacyGObject.test
/usr/share/installed-tests/gjs/testWarnings.sh.test
/usr/share/installed-tests/gjs/detach.test
/usr/share/installed-tests/gjs/testWarnLib.test
/usr/share/installed-tests/gjs/testGObject.test
/usr/share/installed-tests/gjs/testGTypeClass.test
/usr/share/installed-tests/gjs/testCairo.test
/usr/share/installed-tests/gjs/testPromise.test
/usr/share/installed-tests/gjs/set.test
/usr/share/installed-tests/gjs/testGettext.test
/usr/share/installed-tests/gjs/testFundamental.test
/usr/share/installed-tests/gjs/sourcemap-inlined.test
/usr/share/installed-tests/gjs/testAsync.test
/usr/share/installed-tests/gjs/testExceptions.test
/usr/share/installed-tests/gjs/testCommandLine.sh.test
/usr/share/installed-tests/gjs/testEncoding.test
/usr/share/installed-tests/gjs/testConsole.test
/usr/share/installed-tests/gjs/frame.test
/usr/share/installed-tests/gjs/testFormat.test
/usr/share/installed-tests/gjs/testGObjectInterface.test
/usr/share/installed-tests/gjs/step.test
/usr/share/installed-tests/gjs/return.test
/usr/share/installed-tests/gjs/next.test
/usr/share/installed-tests/gjs/testGObjectClass.test
/usr/share/installed-tests/gjs/testCommandLineModules.sh.test
/usr/share/installed-tests/gjs/testAsyncMainloop.test
/usr/share/installed-tests/gjs/sourcemap-inlined-module.test
/usr/share/installed-tests/gjs/testMainloop.test
/usr/share/installed-tests/gjs/testGtk4Warnings.sh.test
/usr/share/installed-tests/gjs/testGObjectDestructionAccess.test
/usr/share/installed-tests/gjs/testImporter.test
/usr/share/installed-tests/gjs/sourcemap-separate.test
/usr/share/installed-tests/gjs/testUtility.test
/usr/share/installed-tests/gjs/testOverrides.test
/usr/share/installed-tests/gjs/finish.test
/usr/share/installed-tests/gjs/testImporter2.test
/usr/share/installed-tests/gjs/testSystem.test
/usr/share/installed-tests/gjs/testLegacyCairo.test
/usr/share/installed-tests/gjs/testSignals.test
/usr/share/installed-tests/gjs/delete.test
/usr/share/installed-tests/gjs/testTimers.test
/usr/share/installed-tests/gjs/quit.test
/usr/share/installed-tests/gjs/testself.test
/usr/share/installed-tests/gjs/testLegacyClass.test
/usr/share/installed-tests/gjs/continue.test
/usr/share/installed-tests/gjs/testIntrospection.test
/usr/share/installed-tests/gjs/testGdkPixbuf.test
/usr/share/installed-tests/gjs/testRegress.test
/usr/share/installed-tests/gjs/testESModules.test
/usr/share/installed-tests/gjs/lastvalues.test
/usr/share/installed-tests/gjs/testLang.test
/usr/share/installed-tests/gjs/testWeakRef.test
/usr/share/installed-tests/gjs/backtrace.test
/usr/share/installed-tests/gjs/testGLibLogWriter.test
/usr/share/installed-tests/gjs/print.test
/usr/share/glib-2.0/schemas
/usr/share/glib-2.0/schemas/gschemas.compiled
/usr/share/gjs-1.0/lsan
/usr/share/gjs-1.0/valgrind
/usr/bin
/usr/bin/gjs
/usr/bin/gjs-console
/usr/libexec/installed-tests/gjs
/usr/libexec/installed-tests/gjs/scripts
/usr/libexec/installed-tests/gjs/GjsTestTools-1.0.typelib
/usr/libexec/installed-tests/gjs/minijasmine
/usr/libexec/installed-tests/gjs/libgimarshallingtests.so
/usr/libexec/installed-tests/gjs/libwarnlib.so
/usr/libexec/installed-tests/gjs/Utility-1.0.typelib
/usr/libexec/installed-tests/gjs/Regress-1.0.typelib
/usr/libexec/installed-tests/gjs/GIMarshallingTests-1.0.typelib
/usr/libexec/installed-tests/gjs/libgjstesttools.so
/usr/libexec/installed-tests/gjs/debugger
/usr/libexec/installed-tests/gjs/WarnLib-1.0.typelib
/usr/libexec/installed-tests/gjs/js
/usr/libexec/installed-tests/gjs/js/modules
/usr/libexec/installed-tests/gjs/js/modules/overrides
/usr/libexec/installed-tests/gjs/js/modules/mutualImport
/usr/libexec/installed-tests/gjs/js/modules/subA/subB
/usr/libexec/installed-tests/gjs/js/modules/badOverrides
/usr/libexec/installed-tests/gjs/js/modules/subErrorInit
/usr/libexec/installed-tests/gjs/js/modules/subBadInit
/usr/libexec/installed-tests/gjs/js/modules/badOverrides2
/usr/libexec/installed-tests/gjs/libregress.so
/usr/libexec/installed-tests/gjs/libutility.so
/usr/libexec/installed-tests/gjs/RegressUnix-1.0.typelib
/usr/include/gjs-1.0/gjs
/lib/gjs/girepository-1.0
/lib/pkgconfig
/lib/libgjs.so.0
/lib/libgjs.so
