0.4.42
/usr/bin
/usr/bin/orc-bugreport
/usr/bin/orcc
/usr/include/orc-0.4/orc
/usr/include/orc-0.4/orc-test
/usr/lib
/usr/lib/liborc-0.4.so
/usr/lib/liborc-0.4.so.0
/usr/lib/liborc-0.4.so.0.42.0
/usr/lib/liborc-test-0.4.so
/usr/lib/liborc-test-0.4.so.0
/usr/lib/liborc-test-0.4.so.0.42.0
/usr/lib/pkgconfig
/usr/lib/pkgconfig/orc-0.4.pc
/usr/lib/pkgconfig/orc-test-0.4.pc
